# Generated by Django 4.1.5 on 2023-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductID", models.AutoField(primary_key=True, serialize=False)),
                ("ProductName", models.CharField(max_length=30)),
                ("ProductCost", models.FloatField(max_length=6)),
            ],
        ),
    ]
