# Generated by Django 4.0.2 on 2023-04-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('Product', models.IntegerField()),
                ('ProductCost', models.FloatField()),
                ('ProductDesc', models.CharField(blank=True, max_length=30)),
                ('ProductQty', models.IntegerField()),
                ('Discount', models.CharField(blank=True, max_length=30)),
                ('Finalprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True)),
                ('Server', models.CharField(max_length=30)),
                ('Table', models.CharField(max_length=30)),
                ('PaymentOption', models.CharField(max_length=30)),
                ('PWDS', models.CharField(max_length=30)),
                ('Tendered', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductCost', models.FloatField(max_length=6)),
            ],
        ),
    ]
