# Generated by Django 4.0.2 on 2023-05-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('StockID', models.AutoField(primary_key=True, serialize=False)),
                ('Stockname', models.CharField(max_length=30)),
                ('Stockqty', models.IntegerField()),
            ],
        ),
    ]
