# Generated by Django 4.0.2 on 2023-03-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now=True)),
                ('Server', models.CharField(max_length=30)),
                ('Table', models.CharField(max_length=30)),
                ('PaymentOption', models.CharField(max_length=30)),
                ('PWDS', models.BooleanField()),
            ],
        ),
    ]
