# Generated by Django 4.0.2 on 2023-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='PWDS',
            field=models.CharField(max_length=30),
        ),
    ]
