# Generated by Django 4.0.2 on 2023-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductStock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
