# Generated by Django 4.0.2 on 2023-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_pwds'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductCost', models.FloatField(max_length=6)),
            ],
        ),
    ]
