# Generated by Django 4.0.2 on 2023-05-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
