# Generated by Django 4.0.2 on 2023-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orders_ordertotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
    ]
