# Generated by Django 4.0.2 on 2023-03-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_productid_test_orderid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
