# Generated by Django 4.0.2 on 2023-03-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='PWDS',
        ),
        migrations.RemoveField(
            model_name='order',
            name='PaymentOption',
        ),
        migrations.AlterField(
            model_name='order',
            name='Table',
            field=models.FloatField(max_length=6),
        ),
    ]
