# Generated by Django 4.0.2 on 2023-03-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_table_order_productcost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='test',
        ),
    ]
