# Generated by Django 4.0.2 on 2023-03-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_order_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='ProductName',
            new_name='Server',
        ),
    ]
