# Generated by Django 4.0.2 on 2023-03-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_test_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
