# Generated by Django 4.0.2 on 2023-03-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_test_productid_test_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
