# Generated by Django 4.0.2 on 2023-03-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.orders')),
            ],
        ),
    ]
