# Generated by Django 4.0.2 on 2023-03-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='ProductID',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
