# Generated by Django 4.0.2 on 2023-03-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_orderline_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='ProductID',
            new_name='Product',
        ),
    ]
