# Generated by Django 4.0.2 on 2023-03-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rename_productid_orderline_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderline',
            new_name='Orderlines',
        ),
    ]
