# Generated by Django 4.0.2 on 2023-03-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_orderline_orderlines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orderlines',
            new_name='Orderline',
        ),
    ]
