# Generated by Django 4.0.2 on 2023-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_rename_orderline_orderlines_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlines',
            name='OrderID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='Product',
            field=models.IntegerField(),
        ),
    ]
