# Generated by Django 4.1.5 on 2023-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_alter_orders_tendered"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
